### ISSUE TITLE
Call to undefined function mysql_connect()

### ISSUE THREAD

**Issue by gamonoid** [gamonoid/issues#281]
**[Original report](https://bitbucket.org/thilina/icehrm-opensource/issue/281) by Satheesh Kumar A S (Sathe) (Bitbucket: [satheesh420](https://bitbucket.org/satheesh420), GitHub: [satheesh420](https://github.com/satheesh420)).**

----------------------------------------

I have tried manual installation from http://icehrm-blog.gamonoid.com/ice-hrm-manual-installation
After the installation, I am able to see only a blank screen with HTTP 500

Below is the information from the log.

21-Sep-2017 15:53:16 Asia/Colombo] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in D:\Tools\xampp_portable\htdocs\icehrm\lib\adodb512\drivers\adodb-mysql.inc.php:364
Stack trace:
#0 D:\Tools\xampp_portable\htdocs\icehrm\lib\adodb512\adodb.inc.php(525): ADODB_mysql->_connect('localhost', 'icehrmuser', '9quRuPoV0C7PVsh...', 'icehrmdb')
#1 D:\Tools\xampp_portable\htdocs\icehrm\lib\adodb512\adodb.inc.php(4323): ADOConnection->Connect('localhost', 'icehrmuser', '9quRuPoV0C7PVsh...', 'icehrmdb')
#2 D:\Tools\xampp_portable\htdocs\icehrm\lib\adodb512\adodb.inc.php(4159): ADONewConnection('mysql')
#3 D:\Tools\xampp_portable\htdocs\icehrm\server.includes.inc.php(27): NewADOConnection('mysql://icehrmu...')
#4 D:\Tools\xampp_portable\htdocs\icehrm\login.php(5): include('D:\\Tools\\xampp_...')
#5 D:\Tools\xampp_portable\htdocs\icehrm\app\login.php(3): include('D:\\Tools\\xampp_...')
#6 {main}
  thrown in D:\Tools\xampp_portable\htdocs\icehrm\lib\adodb512\drivers\adodb-mysql.inc.php on line 364

**PHP Version 7.0.23**
**ICE Version 20.0**

**Comment by gamonoid** [comment]
**Original comment by Thilina Hasantha (Bitbucket: [thilina](https://bitbucket.org/thilina), GitHub: [thilina](https://github.com/thilina)).**

----------------------------------------

Fixed
This was a problem with the out dated documentation link
